### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by bglebrun** [activecm/rita#472] opened 2019-06-13 23:15 UTC
The script `install.sh` should be updated to support the new Ubuntu LTS release 18.04 bionic. Currently as tested on a machine running 18.04 right now, the script freezes when installing bro and doesn't make it to the mongodb installation; potentially when installing the ja3 module/cert logging config.

**Comment by william-stearns** [comment] 2019-06-14 19:10
Unfortunately, we can't do that for the Bro sensors.  The ssl libraries were changed between 16.x and 18.x, and Bro/Zeek is not compatible with the new SSL libraries.  I suspect it is possible to run AI-Hunter inside Ubuntu 18.x, but I suspect it would lead to support calls from customers using 18.x for both systems.  We can revisit this when Zeek fixes their ssl compatibility.

**Comment by ethack** [comment] 2019-06-14 19:22
@william-stearns Could you elaborate a little on what issue this causes so that we can track its progress? For instance, do you have a link to a Bro mailing list or issue tracker ticket that discusses the problem/fix we need? Or do you have any insight as to what actually fails? 

We can install Bro using [the package in Ubuntu's package repository](https://launchpad.net/ubuntu/bionic/+source/bro), which looks like it installs [this version of libssl](https://launchpad.net/ubuntu/bionic/+package/libssl-dev). I presume that it is compatible since that's the version the package maintainer references. I've mentioned that I've successfully installed Bro on 18.04 but if there's a problem that you know of regarding the ja3 module or ssl.log that the SSL incompatibility you mentioned causes it would be useful to have some more insight.

**Comment by william-stearns** [comment] 2019-06-14 21:03
Ubuntu changed SSL libraries when it went to 18.x.  The new libraries don't provide the same set of functions as the old openssl libraries, and so when one compiles Bro it doesn't have the same support functions it needs to handle ssl/tls connections.  Zeek doesn't offer a precompiled binary for ubuntu >17.x - see https://www.zeek.org/download/packages.html .
I'm not surprised that someone's gotten bro to compile on 18.04 since I last ran into this problem, but the fact that the zeek guys still don't offer it makes me think that the version you're using has disabled some of the problematic SSL code.
Note that the version in Ubuntu's repository hasn't been updated since March of 2018.

**Comment by william-stearns** [comment] 2019-06-14 21:24
Finally found the post:
http://mailman.icsi.berkeley.edu/pipermail/zeek/2018-June/013315.html

"Patch (with quite a bit of additional work) is in master. However notice 
that the patch ports "most" of Bro to OpenSSL 1.1, not all.

Thus the patch is in and Bro still does not compile with 1.1 yet. We are 
a bit special because we use a lot of their features - and porting 
everything over is a significant amount of work.

Johanna"

**Comment by ethack** [comment] 2019-06-14 22:15
Thank you, that was very helpful!  I did a little further digging and think we have a couple options we can move forward with.
1. Use the unadvertised Zeek packages
1. Try it out ourselves
1. Ask the Ubuntu package maintainer what the status is

The "someone" you mention getting it to compile looks to be Seth Hall so it's not like it's a random person. We may be able to reach out to him directly and ask if there are any problems we might run into.

The mailing list you posted had a dead link to a patch, but I think I found it [here](https://sources.debian.org/patches/bro/2.5.5-1/). Note that both the mailing list link and these patches apply to the Debian repos and not Ubuntu directly. So if Ubuntu's doesn't work out we could also try the one in Debian. Also, it looks like you were spot on with your guess about disabling problematic SSL code. But the good news is that based on the patch notes, I don't think it's a feature we rely on. It says "Disable OCSP features that can't yet be ported...". For our certificate analysis it's possible that one of the status messages in ssl.log is a revoked certificate but even if that's the case we may still be able to use the remaining features.

You're right that Zeek doesn't have instructions on their website for Ubuntu 18.04 but if you browse [their package repo](http://download.opensuse.org/repositories/network:/bro/xUbuntu_18.04/amd64/) (warning this link is slow to load) they do actually have packages for Ubuntu. It looks like their website is just really outdated because the paths they list for Ubuntu 17.04 and 16.10 don't even exist in the package repo anymore. I saw we go this route first and see what happens. @bglebrun could you test out these commands and see what version of Bro you get (if any)? It looks like 2.6.1 is the version we want to see.

```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/network:/bro/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/bro.list"
sudo apt-get update
sudo apt-get install bro broctl
```

**Comment by william-stearns** [comment] 2019-06-14 22:25
Good afternoon, Ethan,
    I chatted with Ben.  It appears this isn’t from a customer request, but
rather because he has an Ubuntu 18.04 system at home and wanted to do
development on it.
    I’d like to ask that we set this aside.  Ben, please install docker,
virtualbox, or VMware and put Ubuntu 16.04 on it to do development on Bro.
If that’s not possible, spin up a VM on DigitalOcean.  Lisa has pointed out
that she doesn’t want the developers distracted, and I’m guessing we’ve
chewed up at least 8 hours between us on something that has not been
requested by any customer.
     Cheers,
    - Bill

**Comment by bglebrun** [comment] 2019-06-14 22:25
Yeah of course, for me it's not a productivity ending issue, I was just asked to look into it

**Comment by bkonsela** [comment] 2019-09-04 20:12
Hello, everyone. I'm taking over this task.

I'm going through the list of links provided so far in this issue to get a better grasp on the issue.

So far, I went to the Zeek packages page (https://www.zeek.org/download/packages.html) posted earlier, and noticed that the documentation seems to be outdated with the state of the repository. The commands listed for Ubuntu 17.04 give a 404 error. Out of curiosity, I manually navigated to the repository and found that there is now a repository for 18.04, and I was able to install Bro on my Ubuntu 18.04 virtual machine without issue.

I will now attempt to install from source to verify that the issue is no longer present. I am also looking into the reported SSL errors to ensure that the issues that we were encountering are fixed in a way that we are satisfied with.

More soon. Cheers.

**Comment by bkonsela** [comment] 2019-09-05 03:16
I have successfully installed from source using the install documentation (https://docs.zeek.org/en/stable/install/install.html). This seems to work as well. I need to do a bit more testing to see if it is working properly.

I am still looking into the reported SSL issues, and will report on them when I find something.

**Comment by bkonsela** [comment] 2019-11-05 21:50
Hello, I've been working on a patch to install.sh, and just pushed to branch `472-install-script-update-18.04`. It's pending review but addresses issues with Mongo on Bionic.

For reference, using the codename "xenial" for mongo installations fixes the issue of not being able to install Mongo 3.6 onto Ubuntu 18.04. This is per documentation found here: https://linuxconfig.org/how-to-install-latest-mongodb-on-ubuntu-18-04-bionic-beaver-linux

I will open up a pull request shortly for this branch, so the changes can be reviewed. The changes to install.sh are minimal, given the fact that I already identified Bro/Zeek to be a non-issue. Mongo just wasn't playing nice, which I've noticed is a trend.

Hopefully this resolves the issue. I look forward to being able to support Ubuntu 18.04!

**Comment by william-stearns** [comment] 2019-11-05 21:54
What did you find out about the SSL issues?

**Comment by bkonsela** [comment] 2019-11-05 22:05
As far as my research showed, I did not find any SSL issues, certainly none that proved prohibitive to installing Bro/Zeek on Ubuntu 18.04.

Additionally, the link that you provided (https://www.zeek.org/download/packages.html) did not have a 17.04 option, which caused a 404 error in `apt`. I did a manual traversal of their repository and found that there is a directory for Ubuntu 18.04. Using that link for my repository worked like a charm.

For reference, I traversed here: http://download.opensuse.org/repositories/network:/bro/. I hope this answer is satisfactory.

**Comment by bkonsela** [comment] 2019-11-05 22:09
I should also note that, to avoid contamination, I developed my changes on a fresh Ubuntu 18.04 virtual machine, alongside my standard Ubuntu 18.04 development virtual machine.

**Comment by william-stearns** [comment] 2019-11-05 22:11
What research did you do?  Did you contact Seth Hall about the SSL compatibility issues?  Were you able to find someone that was able to say the 18.04 porting issues had been handled?  I recognize that packages are available in 18.04, but it's not clear whether the port had been finished since the icsi.berkeley.edu post was made, or whether these packages simply disabled features to get the code to compile.

**Comment by lisaSW** [comment] 2019-11-05 22:28
@william-stearns , There was an official release of bro for 18.04 as of October 30th. There is no reason or evidence to assume that this issue affects it, as the email you linked references an unofficial version and is almost a year old. Testing was performed on the whole pipeline by @bkonsela and @carrohan by generating beacons, using bro, piping into rita and confirming results with AI-Hunter. This is sufficient and confirms the functionality we were looking for.

**Comment by william-stearns** [comment] 2019-11-05 22:43
From Ethan:
"I did a little digging and found this, which is quite convincing to me.
https://github.com/zeek/zeek/commit/a251b32d85c3a5f45fb50d3fd97c5c2a426007e5
Notable points:
- NEWS doc claims "Bro now supports OpenSSL 1.1."
- Manual compilation instructions removed the directive to install libssl1.0-dev on Ubuntu 18.04."
So it appears the SSL issues have been resolved.

**Closed** 2019-11-13 21:54 UTC
Labels: needs review
