### ISSUE TITLE
Certificate Analysis

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#56] opened 2017-05-08 21:08 UTC
Bro collects x509 data for every certificate it sees. https://www.bro.org/sphinx/scripts/base/init-bare.bro.html#type-X509::Certificate

We can use this data to find new certificates and identify riskier certificate chains.

**Comment by strandjs** [comment] 2017-05-09 09:40
I think a simple review would be to simply look at the age of the certs.  

Then, alert on anything from Symantec...

**Comment by lisaSW** [comment] 2019-02-25 19:01
Duplicate of #179 and #406

**Closed by lisaSW** 2019-02-25 19:01 UTC
Labels: Ice Box, P3, feature
