### ISSUE TITLE
option to save HTML files to a specific location

### ISSUE THREAD

**Issue by cbrenton-acm** [activecm/rita#645] opened 2021-06-03 14:50 UTC
Currently, when you run "rita html-report", a directory with the name of the database is created in the current working directory. RITA then stores an HTML version of its report in this location. This is fine when the command is being run manually but is problematic if the user wishes to automate the process via cron or similar. 

The above command should accept input which lets the user identify where the HTML report directory should be located. Something like:
rita html-report /var/www <database name>

or similar.

**Comment by ethack** [comment] 2021-07-13 13:46
This is a duplicate of https://github.com/activecm/rita/issues/521

There's a pull request open [here](https://github.com/activecm/rita/pull/571) that needs to be tested and updated.

**Closed by ethack** 2021-07-13 13:46 UTC
Labels: feature
